### ISSUE TITLE
Not sure about the preprocess parameter of 'lam'  and 'Pd' for Neurofinder dataset in STNeuroNet.

### ISSUE THREAD

**Issue by zimo-5kk** [YijunBao/SUNS_paper_reproduction#1]
![image](https://user-images.githubusercontent.com/83194946/188781855-90a8233b-33b8-4325-800f-31cd97881999.png)
I have detailed read the STNeuroNet, the paper only show us the parameter of d'(min) for the Neurofinder dataset ,which didn't tell us how to set the preprocess parameter of 'lam'  and 'Pd' for Neurofinder dataset. 
I roughly set lam=2.8,Pd=1-0.037 to make sure d'(min)=1.74 for  Neurofinder dataset. 
Could you tell me the value of 'lam' and 'Pd' you use in your repoduction,thanks a lot!

![db12996f7428aec99a48d6f3ac93b37](https://user-images.githubusercontent.com/83194946/188889950-f0da3c48-c0f9-4278-b945-07081a15ac79.png)

**Comment by YijunBao** [comment]
After reading my previous progress reports, I think I used lam = 2.9 and Pd = 1 - 0.035 (the default values) throughout all datasets. I tried changing the values to match the d' in the STNeuroNet paper, but the resulting F1 decreased. 
As a reference, Sommayyeh told me that she used lam = 1.5, Pd = 0.8 for Neurofinder videos. However, she temporally binned all Neurofinder videos to 3 Hz and binned all ABO videos to 6 Hz, but I did not temporally bin any video, so the optimal parameter in her paper can be different from the optimal parameter in my paper.

**Comment by zimo-5kk** [comment]
Thank you very much for your prompt reply! 
May I ask you the length of the ABO/Neurofinder video you used in the Shallow Unet？
Can I  use all of the Neurofinder data and 1/5 length of ABO data to match the GT masks drawed in /STNeuronNet/Markings/Neurofinder/train(test)/Grader1/ and /STNeuronNet/Markings/ABO/Layer275(Layer175)/FinalGT/?

**Comment by YijunBao** [comment]
Yes, the GT masks are for 1/5 length of ABO videos and full length of Neurofinder videos.

**Comment by zimo-5kk** [comment]
Thank you very much for your help!
